spring:
  application:
    name: Config-Default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fecth-register: true
    regiter-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
